notechondria/notechondria/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path,re_path
from django.views.static import serve
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from . import views

urlpatterns = [
    # debugger url: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
    path("__debug__/", include("debug_toolbar.urls")),
    path('',views.home,name="home"),
    path('notes/', include(('notes.urls','notes'),namespace='notes')),
    path('creators/', include(('creators.urls','creators'),namespace='creators')),
    path('gptutils/', include(('gptutils.urls','recipes'),namespace='gptutils')),
    path("memcsv/",include(("memcsv.urls","memcsv"),namespace='memcsv')),
    path('about/',views.about,name="about"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('search/',views.about,name="search"),
    path('admin/', admin.site.urls),
    # setting icon
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("images/bug-fill.ico" if settings.DEBUG else "images/bar-chart-steps.ico")),
    ),
    path('api-auth/', include('rest_framework.urls')),
   
]

# ... the rest of your URLconf goes here ...
# regex the path request with media in current directory
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

# config for monaco-editor js
# self-made solution for: django.request.log_response:241- 'Not Found: /min-maps/vs/base/common/worker/simpleWorker.nls.js.map'
urlpatterns += [
    re_path(
        r"^min-maps/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.STATIC_ROOT+"monaco-editor/min-maps/",
        },
    ),
]

notechondria/notes/urls.py
"""
Mapping the url request

This file maps the url request from member app and share it with notechondria.url
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_notes, name='notes'),
    path('blocks/new',views.create_block,name='create_noteblock'),
    path('notes/new',views.create_note,name='create_note'),
    path('collections/edit/<int:note_id>',views.edit_note,name='edit_note'),
    path('collections/edit_block/<int:noteblock_id>',views.edit_block,name='edit_noteblock'),
    path('collections/insert_block/<int:note_id>/<int:noteblock_id>',views.insert_block,name='insert_noteblock'),
    path('collections/delete_block/<int:noteblock_id>',views.delete_block,name='delete_noteblock'),
    path('collections/delete_index/<int:noteIndex_id>',views.delete_blockIndex,name='delete_blockIndex'),
    path('collections/reorder_blocks/<int:note_id>',views.reorder_blocks,name='reorder_blocks'),
    path('collections/',views.list_notes,name='list_notes'),
    path('collections/<int:note_id>',views.view_note,name='view_note'),
    path('collections/block/<int:noteblock_id>',views.view_block,name='view_noteblock'),
]

notechondria/notes/views.py
"""
This is where you handle requests (front-end)
Also, you can modify models here (back-end)
"""
import datetime
import json
import logging
import re

from django.http import HttpResponseNotFound
from django.views.decorators.http import require_POST, require_GET
from notechondria.utils import get_object_or_None,generate_unique_id,load_form_error_to_messages,check_is_creator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from creators.models import Creator
from .models import Note, NoteBlock, NoteIndex, Tag, ValidationRecord, NoteBlockTypeChoices, NoteIndex
from .forms import NoteForm, NoteBlockForm
from django.contrib import messages
from .mark_down_parser import md_to_html,clean_block_string

logger=logging.getLogger()

# Create your views here.

@login_required
@require_GET
def list_notes(request):
    """ render list of notes for user, search will using post requests

    Returns:
        request.GET: return list of notes and noteblocks created by user, or 404 if user not exists.
        request.POST: return searched result of the post request.
    """
    context={}
    owner_id = get_object_or_404(Creator, user_id=request.user)
    # in this step, we only add user's notes
    note_list= NoteIndex.objects.filter(note_id__creator_id=owner_id).distinct('note_id')
    # for other queries, use NoteIndex.objects.union()
    context["note_list"]=note_list
    # and user's noteblock
    noteblock_list= NoteBlock.objects.filter(creator_id=owner_id,note_id=None)
    # for other queries, use NoteIndex.objects.union()
    context["noteblock_list"]=noteblock_list
    return render(request,"note_list.html",context=context)


# model-formsets reference: https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/#model-formsets
@login_required
def edit_note(request, note_id):
    """I will not use formset because there are too many restrictions and don't support many to many field.
    this function supports for block editor and code editor
    
    Args:
        note_id: id of Note

    Returns:
        request: return note editor with note meta form, noteIndex as handlers.
    
    """
    context={}
    # load basic context
    owner_id,note_instance=check_is_creator(request, Note, "edit", pk=note_id)
    # test ownership
    if owner_id==None:
        messages.warning(request,"You don't have access to this page.")
        return redirect("home")
    if request.method == "POST":
        # default save method is for block_editor
        save_method=request.POST.get("save_method", "form")
        if save_method=="form":
            # we might at feature photo form each post, so just assume have files
            note_form = NoteForm(
                request.POST, request.FILES, instance=note_instance
            )
            if not note_form.is_valid():
                for key, value in note_form.errors.items():
                    messages.error(request, f"validation error on field {key}:{[error for error in value]}")
                return redirect("notes:edit_note", note_id=note_id)
            note_instance = note_form.save(commit=False)
            note_instance.save()
            # success
            messages.success(request,"edit note block success")
            context["note_form"]=note_form
        elif save_method=="code":
            # debug
            # logger.info(request.POST)
            md_str=request.POST.get("md_str", None)
            logger.info(md_to_html(md_str))
            # test if note exist
            context["note_form"] = NoteForm(instance=note_instance)
            context["savetime"]=datetime.datetime.now()
            return render(request,"htmx_code_save_bar.html",context=context)
    # process get request
    else:
        # test if note exist
        context["note_form"] = NoteForm(instance=note_instance)
        # noteblocks
        note_indexes= NoteIndex.objects.filter(note_id=note_instance).order_by("index")
        context["noteblocks_list"] = note_indexes
        context["note_md"]='\n\n'.join([i.noteblock_id.get_md_str() for i in note_indexes])
    return render(request,"note_editor.html",context=context)

@login_required
def edit_block(request, noteblock_id):
    """Edit single block using htmx, not responsible for edit block reference (NoteIndex) and this feature should be implement in the future.

    Args:
        note_handle_id: id of NoteBlock handle object, creation of note block on the process is handled by insert_block function, if the current handle is not root handle, then we may return a **reference form** (to be implemented)

    Returns:
        request: return saved htmx form
    
    """
    context={}
    owner_id,prev_instance=check_is_creator(request, NoteBlock, "edit", pk=noteblock_id)
    if owner_id==None:
        return render(request,"htmx_edit_noteblock.html",context=context)
    # create new noteblock
    noteblock_form = NoteBlockForm()
    # load handle parameters
    # check root handle
    if prev_instance.note_id==None:
        messages.error(request,"Noteblock is corrupted, note_id not found where it is expected to be found.")
        return render(request,"htmx_edit_noteblock.html",context=context)
    note_handle_instance=get_object_or_None(NoteIndex,note_id=prev_instance.note_id, noteblock_id=prev_instance)
    # load noteblock handle
    context["noteblock_handle"]=note_handle_instance
    if request.method=="POST":
        save_method=request.POST.get("method", "form")
        if save_method=="form":
            noteblock_form=NoteBlockForm(request.POST,request.FILES,instance=prev_instance)
            # we might at feature photo form each post, so just assume have files
            if not noteblock_form.is_valid():
                load_form_error_to_messages(request,noteblock_form)
                return render(request,"htmx_edit_noteblock.html",context=context)
            noteblock_instance=noteblock_form.save(commit=False)
            noteblock_instance.is_AI_generated=request.POST.get('is_AI_generated', '')=='on'
            # test creator id
            # creator_id= get_object_or_None(Creator, user_id=noteblock_form.cleaned_data["creator_id"])
            # if creator_id!=owner_id:
            #     messages.error(request,"Incorrect permission found, we have not implement ownership transfer yet.")
            #     return render(request,"htmx_edit_noteblock.html",context=context)
            noteblock_instance.creator_id=prev_instance.creator_id
            # test note id
            # note_id=get_object_or_None(Note,pk=noteblock_form.cleaned_data["note_id"])
            # if note_id!=prev_instance.note_id:
            #     messages.error(request,"Incorrect note found, we have not implement note transfer yet.")
            #     return render(request,"htmx_edit_noteblock.html",context=context)
            noteblock_instance.note_id=prev_instance.note_id
            # sanitize noteblock string
            noteblock_instance.text=clean_block_string(noteblock_instance.text,noteblock_instance.block_type)
            noteblock_instance.save()
            noteblock_form = NoteBlockForm(instance=noteblock_instance,auto_id=f"nb_{noteblock_instance.id}_id_%s")
        elif save_method=="code":
            # debug
            logger.info(request.POST)
            
            context["noteblock_form"]=noteblock_form
            context["noteblock_md"]=noteblock_form.instance.get_md_str()
            return render(request,"note_code_editor.html",context=context)
    # render get request
    # update if there exists an instance for requested
    else:
        noteblock_form = NoteBlockForm(instance=prev_instance,auto_id=f"nb_{prev_instance.id}_id_%s")
    context["noteblock_form"]=noteblock_form
    context["noteblock_md"]=noteblock_form.instance.get_md_str()
    return render(request,"htmx_edit_noteblock.html",context=context)

@login_required
@require_POST
def insert_block(request, note_id, noteblock_id):
    """insert before the noteblock_id and create new noteblock with handler, process post request only (security)
    No self referencing should be allowed, or the code needs to be change dramatically. and insert reference should be implement separately.
    
    Args:
        noteblock_id: id of NoteBlock object that we need to insert before, 65535 for insert on the last.

    Returns:
        htmx note block editor to refresh handle references
    
    """
    context={}
    if request.method=="POST":
        owner_id,note_instance= check_is_creator(request, Note, "insert block", pk=note_id)
        if owner_id==None:
            return render(request,"note_block_editor.html",context=context)
        noteblock_handlers=list(NoteIndex.objects.filter(note_id=note_id).order_by("index"))
        new_block=NoteBlock.objects.create(creator_id=owner_id,note_id=note_instance,block_type=NoteBlockTypeChoices.TEXT,is_AI_generated=False,text="")
        # add to end
        if noteblock_id==65535:
            NoteIndex.objects.create(note_id=note_instance,index=noteblock_handlers[-1].index+1,noteblock_id=new_block)
            # messages.success("insert section on end success")
            # reload context
            context["noteblocks_list"]=NoteIndex.objects.filter(note_id=note_id).order_by("index")
            context["note_form"]=NoteForm(instance=note_instance)
            return render(request,"note_block_editor.html",context=context)
        
        # do normal moving and insert
        noteblock_instance=get_object_or_None(NoteBlock, pk=noteblock_id)
        if noteblock_instance==None:
            messages.error(request,"noteblock instance not found.")
            return render(request,"note_block_editor.html",context=context)
        noteblock_target_handler=get_object_or_None(NoteIndex,note_id=note_id,noteblock_id=noteblock_id)
        if noteblock_target_handler==None:
            messages.error(request,"noteblock handle not found")

notechondria/notes/templates/htmx_block_remove.html
<div class="modal fade" id="deleteBlockModal" tabindex="-1" aria-labelledby="deleteBlockModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            {% if blocks %}
            <div class="modal-header">
                <h5 class="modal-title" id="deleteBlockModalLabel">Delete chat</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you wish to <strong>DELETE</strong> this block? All the successive message will be lost!
                There is currently no way to restore it.
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-toggle="modal" data-bs-dismiss="modal">Cancel</button>

                <form action="{% url 'notes:delete_noteblock' blocks.noteblock_id.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" id="delete-block-button">Wait 5s</button>
                </form>
                <form action="{% url 'notes:delete_blockIndex' blocks.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-warning" id="delete-reference-button">Wait 3s</button>
                </form>
            </div>
            {% endif %}
            {% include "message_display.html"%}
        </div>
    </div>

    <script>
        // show on load

        $(document).ready(function () {
            $('#deleteBlockModal').modal('show');

            $('#delete-block-button').prop('disabled', true);
            setTimeout(function () {
                $("#delete-block-button").html('Wait 4s');
            }, 1000);
            setTimeout(function () {
                $("#delete-block-button").html('Wait 3s');
            }, 2000);
            setTimeout(function () {
                $("#delete-block-button").html('Wait 2s');
            }, 3000);
            setTimeout(function () {
                $("#delete-block-button").html('Wait 1s');
            }, 4000);
            setTimeout(function () {
                $("#delete-block-button").prop('disabled', false);
                $("#delete-block-button").html('Delete Block');
            }, 5000);

            $('#delete-reference-button').prop('disabled', true);
            setTimeout(function () {
                $("#delete-reference-button").html('Wait 2s');
            }, 1000);
            setTimeout(function () {
                $("#delete-reference-button").html('Wait 1s');
            }, 2000);
            setTimeout(function () {
                $("#delete-reference-button").prop('disabled', false);
                $("#delete-reference-button").html('Delete Reference');
            }, 3000);
        });
    </script>

notechondria/notes/templates/htmx_edit_noteblock.html
{% load static%}
<!-- This template will only be called for note block editor to render noteblocks -->
{% if noteblock_form %}
{% if noteblock_form.instance %}

{% if noteblock_handle %}

</div>
<form hx-post="{% url 'notes:edit_noteblock' noteblock_handle.noteblock_id.id %}" hx-encoding="multipart/form-data"
  hx-vals="unset" hx-swap="outerHTML">
  <div class="card mb-3">
    <div class="card-body row">
      <!-- Use jQuery to hide advanced options -->
      {% csrf_token %}
      <!-- Django overkill form -->
      <!-- Include the hidden fields -->
      {% for hidden in noteblock_form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
      <!-- Include the visible fields  -->
      {% for field in noteblock_form.visible_fields %}
      <!-- {{ field.name }} -->
      {% if field.name == "block_type" %}
      <div class="mb-3 col-md-6">
        {% elif field.name == "is_AI_generated"%}
        
      <div class="mb-3 col-md-6 align-self-end">
        {% else %}
        <div class="mb-3 col-md-12">
          {% endif %}
          {% if field.errors %}
          <div class="alert alert-danger">
            {% for error in field.errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}
          {% if field.name == 'is_AI_generated' %}
          <div class="form-check">
            {% endif %}
            {% if field.help_text %}
            <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus"
              data-bs-content="{{ field.help_text|safe }}">
              <label for="{{ field.id_for_label }}"
                class="{% if field.name == 'is_AI_generated' %} form-check-label {% else %}form-label{% endif %}">
                {{ field.label }}
              </label>
              {{ field }}
            </span>
            {% else %}
            <label for="{{ field.id_for_label }}"
              class="{% if field.name == 'is_AI_generated' %} form-check-label {% else %}form-label{% endif %}">
              {{ field.label }}
            </label>
            {{ field }}
            {% endif %}

            {% if field.name == 'is_AI_generated' %}
          </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="row justify-content-between">
          <div class="col-auto">
            <div hx-get="{% url 'notes:delete_blockIndex' noteblock_handle.id %}" class="btn btn-danger"
              hx-target="#noteblock-delete" hx-swap="innerHTML">Delete</div>
          </div>
          <div class="col-auto">
            <div class="row">
              <div class="col-auto mt-1">Last saved: {{noteblock_form.instance.last_edit}}</div>
              <div class="col-auto">
                <button type="submit" class="btn btn-primary">Save NoteBlock</button>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>

<script src="{% static 'notechondria/js/toggle-noteblock-widgets.js' %}"></script>

<!-- enable popover -->

<script>
  var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
  var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl)
  })
</script>

{% else %}
<div class="alert alert-danger mt-3 ms-3 me-3">
  Note block handle not found.
</div>
{% endif %}
{% else %}
<div class="alert alert-danger mt-3 ms-3 me-3">
  Note block instance not found.
</div>
{% endif %}
{% else %}
<div class="alert alert-danger mt-3 ms-3 me-3">
  Note block not found.
</div>
{% endif %}

{% include "message_display.html"%}

notechondria/notes/templates/monaco_official_sample.html
<!-- reference: https://github.com/microsoft/monaco-editor/blob/main/samples/browser-script-editor/index.html -->
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link
        rel="stylesheet"
        data-name="vs/editor/editor.main"
        href="{% static '/monaco-editor/min/vs/editor/editor.main.css' %}"
    />
</head>
<body>
    <h2>Monaco Editor Sync Loading Sample</h2>
    <div id="codeEditor" style="width: 800px; height: 600px; border: 1px solid grey"></div>

    <script>
        var require = { paths: { vs: "{% static '/monaco-editor/min/vs' %}" } };
    </script>
    <script src="{% static '/monaco-editor/min/vs/loader.js' %}"></script>
    <script src="{% static '/monaco-editor/min/vs/editor/editor.main.nls.js' %}"></script>
    <script src="{% static '/monaco-editor/min/vs/editor/editor.main.js' %}"></script>

    <script>
        var editor = monaco.editor.create(document.getElementById('codeEditor'), {
            value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
            language: 'javascript'
        });
    </script>
</body>

notechondria/notes/templates/note_file_editor.html
Not implemented yet

notechondria/notes/templates/note_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Note lists</title>
    <style>
        .fill-height {
            height: calc(100vh - 102px);
            /* Adjust the navbar height as needed */
        }
    </style>

    {% load static %}

    {% include "resource_header.html" %}
</head>

<body>

    {% include "navbar.html" %}

    <main class="container-fluid mt-3 align-items-center fill-height">
        <div class="row g-2 h-100">
            <div class="col-md-9 h-100">
                <div class="card mb-3 h-100">
                    <div class="card-header">
                        <nav>
                            <div class="nav nav-tabs card-header-tabs" id="nav-tab" role="tablist">
                                <button class="nav-link active" id="nav-note-tab" data-bs-toggle="tab"
                                    data-bs-target="#nav-note" type="button" role="tab" aria-controls="nav-note"
                                    aria-selected="true">
                                    My Note
                                </button>
                                <button class="nav-link" id="nav-noteblock-tab" data-bs-toggle="tab"
                                    data-bs-target="#nav-noteblock" type="button" role="tab"
                                    aria-controls="nav-noteblock" aria-selected="false">
                                    My Noteblocks
                                </button>
                                <button class="nav-link" id="nav-share-tab" data-bs-toggle="tab"
                                    data-bs-target="#nav-share" type="button" role="tab" aria-controls="nav-share"
                                    aria-selected="false" disabled>
                                    Subscription
                                </button>
                            </div>
                        </nav>
                    </div>
                    <div class="tab-content" style="overflow: auto; padding-right: 1px;" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-note" role="tabpanel" aria-labelledby="nav-note"
                            tabindex="0">
                            <div class="card-body">
                                {% if note_list %}
                                <div class="row row-cols-1 row-cols-md-2 g-4">
                                    {% for note_handle in note_list %}
                                    <div class="col">
                                        <div class="card mb-3">
                                            {% if note_handle.get_image != None %}
                                            <img src="{{note_handle.get_image.image.url}}" class="card-img-top"
                                                alt="{{note_handle.get_image.text}}">
                                            {% endif %}
                                            <div class="card-body">
                                                <h2 class="card-title">
                                                    {{note_handle.note_id.title|truncatechars:50}}</h2>
                                                <h5 class="card-subtitle mt-3">
                                                    {{note_handle.note_id.creator_id|truncatechars:50}}</h5>
                                                <p>{{note_handle.note_id.description|truncatechars:300}}</p>
                                                <div class="row justify-content-between">
                                                    <!-- render edit button for owner -->
                                                    {% if request.user == note_handle.note_id.creator_id.user_id %}
                                                    <div class="col-auto me-2">
                                                        <a class="btn btn-secondary"
                                                            href="{% url 'notes:edit_note' note_handle.note_id.id %}">Edit</a>
                                                    </div>
                                                    {% else %}
                                                    <div class="col-auto">
                                                        <!-- place holder for edit button -->
                                                        &nbsp;
                                                    </div>
                                                    {% endif %}
                                                    <div class="col-auto">
                                                        <a class="btn btn-primary"
                                                            href="{% url 'notes:view_note' note_handle.note_id.id %}">View</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <!-- infinite scroll section to be implemented -->
                                {% else %}
                                <div class="card mb-3">
                                    <div class="card-body text-center">
                                        You don't have any note stored in our server yet, please try to create one
                                        <div class="d-flex justify-content-center">
                                            <div class="btn btn-primary mt-3" hx-get="{%url 'notes:create_note' %}"
                                                hx-target="#noteModal" hx-swap="innerHTML">Create notes</div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-noteblock" role="tabpanel" aria-labelledby="nav-noteblock"
                            tabindex="0">
                            <div class="card-body">
                                {% if noteblock_list %}
                                <div class="row row-cols-1 row-cols-md-2 g-4">
                                    {% for noteblock in noteblock_list %}
                                    <div class="col">
                                        <div class="card mb-3">
                                            {% if noteblock.image and noteblock.image != None %}
                                            <img src="{{noteblock.image.url}}" class="card-img-top"
                                                alt="{{noteblock.text}}">
                                            {% endif %}
                                            <div class="card-body">
                                                {% if noteblock.note_id %}
                                                <h5 class="card-title">{{noteblock.note_id|truncatechars:50}}</h5>
                                                {% endif %}
                                                <h6 class="card-subtitle mt-3">
                                                    {{noteblock.note_id.creator_id|truncatechars:50}}</h6>
                                                <p>{{noteblock.text|truncatechars:300}}</p>
                                                <div class="row justify-content-between">
                                                    <!-- render edit button for owner -->
                                                    {% if request.user == noteblock.creator_id.user_id %}
                                                    <div class="col-auto me-2">
                                                        <a class="btn btn-secondary"
                                                            href="{% url 'notes:edit_noteblock' noteblock.id %}">Edit</a>
                                                    </div>
                                                    {% else %}
                                                    <div class="col-auto">
                                                        <!-- place holder for edit button -->
                                                        &nbsp;
                                                    </div>
                                                    {% endif %}
                                                    <div class="col-auto">
                                                        <a class="btn btn-primary"
                                                            href="{% url 'notes:view_noteblock' noteblock.id %}">View</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <!-- infinite scroll section to be implemented -->
                                {% else %}
                                <div class="card mb-3">
                                    <div class="card-body text-center">
                                        You don't have any note stored in our server yet, please try to create one
                                        <div class="d-flex justify-content-center">
                                            <div class="btn btn-primary mt-3" hx-get="{%url 'notes:create_note' %}"
                                                hx-target="#noteModal" hx-swap="innerHTML">Create notes</div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-share" role="tabpanel" aria-labelledby="nav-text-tab"
                            tabindex="0">
                        </div>
                    </div>
                </div>
            </div>
            <aside class="col-md-3 blog-sidebar">
                <!-- Render basic user info -->
                <div class="card h-100 mb-3">
                    <div class="card-body">
                        side panel to be implemented
                    </div>
                </div>
            </aside>
        </div>
    </main>
</body>

<!-- TODO: create footer here -->