notechondria/creators/urls.py
"""
Mapping the url requrest

This file maps the url requrest from member app and share it with notechondria.url
"""

from django.urls import path
from . import views
urlpatterns = [
    path('', views.creators, name='creators'),
    path('login/',views.login_request,name='login'),
    path('register/',views.register_request,name='register'),
    path('profile/<str:username>',views.get_profile,name='profile'),
    path('profile/<str:username>/edit',views.edit_profile,name='edit_profile'),
    path('logout/',views.logout_request,name="logout")
]

notechondria/gptutils/urls.py
"""
Mapping the url request

This file maps the url request from member app and share it with notechondria.url
"""

from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve
from . import views
urlpatterns = [
    path('', views.gptutils, name='main'),
    path('chat/<int:conv_pk>',views.get_chat,name='get_chat'),
    path('chat/stream/<int:conv_pk>',views.get_stream_chat,name='get_stream_chat'),
    path('chat/delete/<int:conv_pk>',views.delete_chat,name='delete_chat'),
    path('chat/edit/<int:conv_pk>',views.edit_chat,name='edit_chat'),
    path('chat/create',views.create_chat,name='create_chat'),
    path('chat/create/fast',views.fast_chat,name='fast_chat'),
    path('chat/edit_message/<int:message_pk>',views.edit_message,name='edit_message'),
    path('chat/delete_message/<int:message_pk>',views.delete_message,name='delete_message'),
    path('chat/resend_message/<int:message_pk>',views.resend_message,name='resend_message'),
]
# redirect media request to media root
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

notechondria/notechondria/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path,re_path
from django.views.static import serve
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from . import views

urlpatterns = [
    # debugger url: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
    path("__debug__/", include("debug_toolbar.urls")),
    path('',views.home,name="home"),
    path('notes/', include(('notes.urls','notes'),namespace='notes')),
    path('creators/', include(('creators.urls','creators'),namespace='creators')),
    path('gptutils/', include(('gptutils.urls','recipes'),namespace='gptutils')),
    path("memcsv/",include(("memcsv.urls","memcsv"),namespace='memcsv')),
    path('about/',views.about,name="about"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('search/',views.about,name="search"),
    path('admin/', admin.site.urls),
    # setting icon
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("images/bug-fill.ico" if settings.DEBUG else "images/bar-chart-steps.ico")),
    ),
    path('api-auth/', include('rest_framework.urls')),
   
]

# ... the rest of your URLconf goes here ...
# regex the path request with media in current directory
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

# config for monaco-editor js
# self-made solution for: django.request.log_response:241- 'Not Found: /min-maps/vs/base/common/worker/simpleWorker.nls.js.map'
urlpatterns += [
    re_path(
        r"^min-maps/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.STATIC_ROOT+"monaco-editor/min-maps/",
        },
    ),
]

notechondria/notes/urls.py
"""
Mapping the url request

This file maps the url request from member app and share it with notechondria.url
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_notes, name='notes'),
    path('blocks/new',views.create_block,name='create_noteblock'),
    path('notes/new',views.create_note,name='create_note'),
    path('collections/edit/<int:note_id>',views.edit_note,name='edit_note'),
    path('collections/edit_block/<int:noteblock_id>',views.edit_block,name='edit_noteblock'),
    path('collections/insert_block/<int:note_id>/<int:noteblock_id>',views.insert_block,name='insert_noteblock'),
    path('collections/delete_block/<int:noteblock_id>',views.delete_block,name='delete_noteblock'),
    path('collections/delete_index/<int:noteIndex_id>',views.delete_blockIndex,name='delete_blockIndex'),
    path('collections/reorder_blocks/<int:note_id>',views.reorder_blocks,name='reorder_blocks'),
    path('collections/',views.list_notes,name='list_notes'),
    path('collections/<int:note_id>',views.view_note,name='view_note'),
    path('collections/block/<int:noteblock_id>',views.view_block,name='view_noteblock'),
]

notechondria/creators/forms.py
"""
Escape from forms

With django built-in validation and everything else!
https://docs.djangoproject.com/en/4.2/topics/forms/
"""
import os
from django.conf import settings
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from django.utils.timezone import now
from PIL import Image
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.password_validation import (
    validate_password,
    get_default_password_validators,
)
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.core.validators import EmailValidator
from .models import Creator, VerificationCode, VerificationChoices
import logging

logger = logging.getLogger("django")


class RepassValidator:
    """validate if the user enter the password correctly"""

    def __init__(self, repassword: str):
        self.repass = repassword

    def validate(self, password, user=None):
        """default validate function"""
        if password != self.repass:
            raise ValidationError(
                _("This password did not match with your re-entered password.")
            )

    def get_help_text(self):
        """return standard help_text"""
        return _("Your password must match with the re-entered password.")


class ResizedImageValidator:
    """validate if the user have cropped the image correctly"""

    def __init__(self, x: int, y: int, width: int, height: int):
        self.x = x
        self.y = y
        self.width = width
        self.height = height

    def validate(self, image: Image, user=None):
        """Validate by inputting the cropping image, raise error if size mismatched"""
        w, h = image.size
        if w < self.x + self.width or h < self.y + self.height:
            raise ValidationError(
                _(
                    "The image size did not match with cropping parameters with expected width %(ew)d, height %(eh)d but actual data recieved is %(w)d, %(h)d"
                ),
                params={
                    "ew": self.x + self.width,
                    "eh": self.y + self.height,
                    "w": w,
                    "h": h,
                },
            )

    def clean(self, image: Image, resize=(500,500)) -> Image:
        """return cleanned image"""
        cropped_image = image.crop(
            (self.x, self.y, self.width + self.x, self.height + self.y)
        )
        return cropped_image.resize(resize, Image.Resampling.LANCZOS)

    def get_help_text(self):
        """return standard help_text"""
        return _("Please try to re-cropping the image or contact admin for bug report")


class LoginForm(forms.Form):
    """Generate login form based on Creator model."""

    username = forms.CharField(
        label="Username",
        validators=[UnicodeUsernameValidator],
        max_length=150,
        required=True,
    )
    password = forms.CharField(
        label="Password", widget=forms.PasswordInput(), required=True
    )

    def __init__(self, *args, **kwargs):
        """add extra arguments for each input,
        reference: https://stackoverflow.com/questions/29716023/add-class-to-form-field-django-modelform
        """
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


def validate_user_name(new_user_name, user=None) -> None:
    """test if username repeated based on server data"""
    if user is not None and user.user_id.username == new_user_name:
        return
    if User.objects.filter(username=new_user_name).exists():
        raise ValidationError(
            _("User name already exists %(server_user_name)s"),
            params={"server_user_name": new_user_name},
        )


def validate_registration_code(code) -> None:
    """Test if the user is eligible for register"""
    if VerificationCode.objects.filter(code=code).exists():
        code_instance = VerificationCode.objects.get(code=code)
        if (
            code_instance.usage == VerificationChoices.REGISTER
            and code_instance.max_use > 0
            and code_instance.expire_date > now()
        ):
            return
    raise ValidationError(
        _("Validation code %(code)s does not exists or expired"),
        params={"code": code},
    )


class RegisterForm(forms.ModelForm):
    """Generate register form based on Creator model."""

    # Guess what? I am LAZY.
    user_name = forms.CharField(
        max_length=150, validators=[UnicodeUsernameValidator], required=True
    )
    register_code = forms.CharField(help_text="The website is currently under testing, only qualified user can register. For further information, please contact site-admin",max_length=150, required=True)
    image = forms.ImageField(
        help_text="To reduce request count, please upload image after you completed all other forms to reduce error rates",
        required=False,
    )
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=True)
    email = forms.CharField(max_length=255, validators=[EmailValidator], required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    repassword = forms.CharField(
        label="Re-enter your password", widget=forms.PasswordInput(), required=True
    )

    # attributes for image cropping
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        """Load meta data for multiple field to generate form

        if you are lazy enough, you can also load meta,
        reference: https://docs.djangoproject.com/en/4.2/ref/forms/fields/
        (search for 'Meta')
        """

        model = Creator
        fields = [
            "image",
            "x",
            "y",
            "width",
            "height",
            "user_name",
            "register_code",
            "first_name",
            "last_name",
            "email",
            "password",
            "repassword",
            "motto",
            "social_link",
        ]

    def __init__(self, *args, **kwargs):
        """add extra arguments for each input,
        reference: https://stackoverflow.com/questions/29716023/add-class-to-form-field-django-modelform
        """
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields["social_link"].required = False
        self.fields["motto"].required = False
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        # prefill instance value, but the function will not be executed if the code is working as expected.
        if self.instance.pk:
            self.fields["user_name"].initial = self.instance.user_id.username
            self.fields["image"].initial = self.instance.image
            self.fields["x"].initial = self.instance.x
            self.fields["y"].initial = self.instance.y
            self.fields["width"].initial = self.instance.width
            self.fields["height"].initial = self.instance.height
            self.fields["first_name"].initial = self.instance.user_id.first_name
            self.fields["last_name"].initial = self.instance.user_id.last_name
            self.fields["email"].initial = self.instance.user_id.email
            self.fields["password"].required = False
            self.fields["repassword"].required = False

    # custom validation
    def clean(self):
        """custom validation for repassword and forbid user registration attack

        check default errors
        check user name repeated
        check if user exist
        validate password
        """
        # check default errors
        if any(self.errors):
            return
        data = self.cleaned_data
        # check if user is invited
        validate_registration_code(data["register_code"])
        # validate password
        repass = RepassValidator(data["repassword"])
        validators = get_default_password_validators()
        validators.append(repass)
        validate_password(data["password"], password_validators=validators)
        # check if user exist
        validate_user_name(data["user_name"])

    def save(self, commit: bool = ...) -> Creator:
        creator_instance = super(RegisterForm, self).save(commit=False)
        # create user
        user = User.objects.create(
            username=self.cleaned_data["user_name"],
            first_name=self.cleaned_data["first_name"],
            last_name=self.cleaned_data["last_name"],
            email=self.cleaned_data["email"],
        )
        user.set_password(self.cleaned_data["password"])
        # the user will not be save automatically
        user.save()
        creator_instance.user_id = user
        # save default image first
        # https://stackoverflow.com/questions/32945292/how-to-save-pillow-image-object-to-django-imagefield
        default_image_file= Image.open(os.path.join(settings.STATIC_ROOT,"images","person-circle.png"))
        buffer = BytesIO()
        default_image_file.save(fp=buffer, format='PNG')
        default_image= ContentFile(buffer.getvalue())
        img_name="profile_latest.png"
        creator_instance.image.save(img_name, InMemoryUploadedFile(
            default_image,       # file
            None,               # field_name
            img_name,           # file name
            'image/png',       # content_type
            default_image.tell,  # size
            None)               # content_type_extra
        )

notechondria/notechondria/views.py
"""
This is where you handle requests (front-end)
Also, you can modify models here (back-end)
"""

from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
import logging

logger = logging.getLogger("django")

def home(request):
    """render default home page"""
    logger.info(f'detected debug mode in django: {settings.DEBUG}')
    return render(request,'index.html',{})

def about(request):
    """render static about page"""
    return render(request,'about.html',{})

def dashboard(request):
    """render static about page"""
    return render(request,'dashboard.html',{})

def search(request):
    """render dynamic search page, process get requests only"""
    messages.warning(request, "function not implemented.")
    return render(request,'index.html',{})

def is_offline(request):
    """context processor for OFFLINE variable in settings
    
    reference:https://stackoverflow.com/questions/433162/can-i-access-constants-in-settings-py-from-templates-in-django
    """
    return {'is_offline': settings.OFFLINE}

notechondria/notechondria/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notechondria About</title>
    <meta charset="UTF-8">

    {% include "resource_header.html" %}
</head>

<body class="vh-100">

    {% include "navbar.html" %}

    <section class="py-5 text-center container my-auto">
        <div class="row">
            <section class="bg-light align-items-center my-auto">
                <h1 id="notechondria" class="display-4 text-center mb-4 mt-4">Notechondria</h1>
                <p class="lead text-center mb-5">Empower your success with the notes you create.</p>

                <p class="text-start mb-4">Last updated on <time datetime="2023-12-04">December 4, 2023</time>.</p>

                <p class="text-start mb-4">
                    Inspired by the synergy of notes and the energy-producing mitochondria, <strong>Notechondria</strong>
                    is designed to be the catalyst for your personal achievements. Our vision extends beyond mere text
                    or sketches on an iPad or other media. We aim to interconnect all forms of data, weaving them into
                    an easily navigable information tapestry tailored to each user.
                </p>

                <h2 class="h4 mb-3">Key Features:</h2>
                <ul class="mb-4 text-start container">
                    <li>Intelligent note-linking with automated tagging powered by generative AI.</li>
                    <li>Enhanced note interpretation and sharing through generative AI.</li>
                    <li>Effortless synchronization of notes across devices and formats, including images, datasets,
                        LaTeX, Markdown, and more.</li>
                    <li>Dynamic, card-like note truncation and automated daily note generation based on user activity.
                    </li>
                </ul>

                <p class="text-start mb-4">
                    We value your privacy and trust. That's why we guarantee that your data will not be shared or sold
                    to any third parties. As primary users of the app, the developers uphold this commitment.
                </p>

                <p class="text-start mb-3">
                    Your knowledge remains yours alone. Leveraging the OpenAI API, we ensure your original ideas and
                    thoughts are never used for AI training purposes, safeguarding the uniqueness of your intellectual
                    property.
                </p>
            </section>
        </div>
    </section>
</body>

<!-- TODO: create footer here -->

notechondria/notechondria/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notechondria</title>
    <meta charset="UTF-8">

    {% include "resource_header.html" %}

    <style>
        .card[data-clickable=true] {
            cursor: pointer;
        }
        .card-img-top {
            object-fit: cover;
            height: 100px;
            width: auto;
        }
    </style>

    {% load static %}
</head>

<body class="vh-100"
    style="background-image: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);">

    {% include "navbar.html" %}

    <section class="mt-3 text-center container-fluid">
        <div class="row row-cols-1 row-cols-md-5 g-4">
            <div class="col">
                <div class="card" data-clickable="true" data-href="https://webstac.wustl.edu/">
                    <img src="https://images.unsplash.com/photo-1460644212565-a64ce7c7094c?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">WebStac</h5>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" data-clickable="true" data-href="https://wustl.instructure.com/">
                    <img src="https://images.unsplash.com/photo-1629652487043-fb2825838f8c?q=80&w=2342&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Canvas</h5>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" data-clickable="true" data-href="https://www.overleaf.com/project">
                    <img src="https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?q=80&w=2279&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Overleaf</h5>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" data-clickable="true" data-href="https://www.gradescope.com/">
                    <img src="https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=2346&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">GradeScope</h5>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" data-clickable="true" data-href="https://webstac.wustl.edu/">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">WebStac</h5>
                    </div>
                </div>
            </div>
        </div>
        </div>

    </section>

    <script>
        // very good solution: https://stackoverflow.com/a/54405654/14110380
        $(document).ready(() => {
            $(document.body).on('click', '.card[data-clickable=true]', (e) => {
                var href = $(e.currentTarget).data('href');
                window.open(href, "_blank");
            });
        });
    </script>
</body>

<!-- TODO: create footer here -->

notechondria/notechondria/templates/htmx_sse_header.html
{% load static %}

{% if is_offline %}
    <script src="{% static 'htmx/htmx.sse.js' %}"></script>
{% else %}
    <script src="https://unpkg.com/htmx.org/dist/ext/sse.js"></script>
{% endif %}

notechondria/notechondria/templates/image_cropping.html
<!-- Code referenced from: https://simpleisbetterthancomplex.com/tutorial/2017/03/02/how-to-crop-images-in-a-django-application.html -->

<!-- load jquery and bootstrap before using the code -->
<!-- load cropper.js before using the code -->
<!-- load jquery-cropper.js before using the code -->
<!-- load cropper.min before using the code -->
<!-- give the form id as formUpload-->
<!-- you must rename the image field id to id_image otherwise the tag will not work. -->

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Crop the photo</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <img src="" id="image" class="img-fluid" style="max-width: 100%;">
            <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                    <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                </div>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Nevermind</button>
                <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        $("#id_image").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1 / 1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
        });

    });
</script>

notechondria/notechondria/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notechondria</title>
    <meta charset="UTF-8">

    {% include "resource_header.html" %}
</head>

<body class="vh-100"
    style="background-image: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);">

    {% include "navbar.html" %}

    <section class="py-5 text-center container">
        <div class="card">
            <div class="card-body row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    Notechondria, our goal is to integrate everything you need in this one site. This should be the
                    gateway to future cloud computing.
                </div>
            </div>
        </div>
    </section>
</body>

<!-- TODO: create footer here -->

notechondria/notechondria/templates/navbar.html
<header class="mb-auto">
    <div class=" fixed-top ">
        <!-- Nav bar use some code from: https://getbootstrap.com/docs/5.3/components/navbar/#scrolling -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Title -->
                <a class="navbar-brand ml-3" href="#">Notechondria</a>
                <!-- Toggle for navigation bar if there is no enough space -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Toggle content (navigation bar) -->
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <!-- Homepage -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <!-- Extra link -->
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'about'%}">About</a>
                        </li>

                        {% if request.user.is_authenticated %}
                        <!-- Extra dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Notes
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{%url 'notes:list_notes' %}">My notes</a></li>
                                <li><div class="dropdown-item" hx-get="{%url 'notes:create_noteblock' %}" hx-target="#noteModal"
                                    hx-swap="innerHTML">Add snippets</div></li>
                                <li><div class="dropdown-item" hx-get="{%url 'notes:create_note' %}" hx-target="#noteModal"
                                    hx-swap="innerHTML">Create notes</div></li>
                            </ul>
                        </li>
                        <!-- Extra dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Utilities
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'gptutils:main' %}">Start conversation</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>

                    <!-- Search bar -->
                    <form class="d-flex ms-auto me-auto" action="{% url 'search' %}" role="search" method="post">
                        {% csrf_token %}
                        <input class="form-control me-2" type="text" name="query"
                            placeholder="{% if query%}{{query}}{% else %}Enter to start search{%endif%}">
                        <button class="btn btn btn-outline-success" type="submit">Search</button>
                    </form>

                    <!-- User info -->
                    {% if request.user.is_authenticated %}
                    <a class="btn btn-primary ms-2 mt-2 mb-2"
                        href="{% url 'creators:profile' request.user.username %}">Setting</a>
                    <a class="btn btn-primary ms-2 mt-2 mb-2" href="{% url 'creators:logout' %}">Logout</a>
                    {% else %}
                    <a class="btn btn-primary ms-2 mt-2 mb-2" href="{% url 'creators:login' %}">Login</a>
                    <!-- TODO: Make this function -->
                    <a class="btn btn-primary ms-2 mt-2 mb-2" href="{% url 'creators:register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% include "message_display.html"%}
    </div>
</header>

<!-- nav-bar placeholder -->

<div style="height: 70px;"></div>

<div id="noteModal">
    <!-- Some dirty code to place modals created by note module -->
</div>