notechondria/gptutils/urls.py
"""
Mapping the url request

This file maps the url request from member app and share it with notechondria.url
"""

from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve
from . import views
urlpatterns = [
    path('', views.gptutils, name='main'),
    path('chat/<int:conv_pk>',views.get_chat,name='get_chat'),
    path('chat/stream/<int:conv_pk>',views.get_stream_chat,name='get_stream_chat'),
    path('chat/delete/<int:conv_pk>',views.delete_chat,name='delete_chat'),
    path('chat/edit/<int:conv_pk>',views.edit_chat,name='edit_chat'),
    path('chat/create',views.create_chat,name='create_chat'),
    path('chat/create/fast',views.fast_chat,name='fast_chat'),
    path('chat/edit_message/<int:message_pk>',views.edit_message,name='edit_message'),
    path('chat/delete_message/<int:message_pk>',views.delete_message,name='delete_message'),
    path('chat/resend_message/<int:message_pk>',views.resend_message,name='resend_message'),
]
# redirect media request to media root
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

notechondria/notechondria/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path,re_path
from django.views.static import serve
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from . import views

urlpatterns = [
    # debugger url: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
    path("__debug__/", include("debug_toolbar.urls")),
    path('',views.home,name="home"),
    path('notes/', include(('notes.urls','notes'),namespace='notes')),
    path('creators/', include(('creators.urls','creators'),namespace='creators')),
    path('gptutils/', include(('gptutils.urls','recipes'),namespace='gptutils')),
    path("memcsv/",include(("memcsv.urls","memcsv"),namespace='memcsv')),
    path('about/',views.about,name="about"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('search/',views.about,name="search"),
    path('admin/', admin.site.urls),
    # setting icon
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("images/bug-fill.ico" if settings.DEBUG else "images/bar-chart-steps.ico")),
    ),
    path('api-auth/', include('rest_framework.urls')),
   
]

# ... the rest of your URLconf goes here ...
# regex the path request with media in current directory
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

# config for monaco-editor js
# self-made solution for: django.request.log_response:241- 'Not Found: /min-maps/vs/base/common/worker/simpleWorker.nls.js.map'
urlpatterns += [
    re_path(
        r"^min-maps/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.STATIC_ROOT+"monaco-editor/min-maps/",
        },
    ),
]

notechondria/notes/urls.py
"""
Mapping the url request

This file maps the url request from member app and share it with notechondria.url
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_notes, name='notes'),
    path('blocks/new',views.create_block,name='create_noteblock'),
    path('notes/new',views.create_note,name='create_note'),
    path('collections/edit/<int:note_id>',views.edit_note,name='edit_note'),
    path('collections/edit_block/<int:noteblock_id>',views.edit_block,name='edit_noteblock'),
    path('collections/insert_block/<int:note_id>/<int:noteblock_id>',views.insert_block,name='insert_noteblock'),
    path('collections/delete_block/<int:noteblock_id>',views.delete_block,name='delete_noteblock'),
    path('collections/delete_index/<int:noteIndex_id>',views.delete_blockIndex,name='delete_blockIndex'),
    path('collections/reorder_blocks/<int:note_id>',views.reorder_blocks,name='reorder_blocks'),
    path('collections/',views.list_notes,name='list_notes'),
    path('collections/<int:note_id>',views.view_note,name='view_note'),
    path('collections/block/<int:noteblock_id>',views.view_block,name='view_noteblock'),
]

notechondria/gptutils/views.py
from datetime import datetime
from django.utils import timezone
import logging
from notechondria.utils import check_is_creator, generate_unique_id, get_object_or_None,load_form_error_to_messages
from django.http import StreamingHttpResponse
from django.views.decorators.http import require_POST,require_GET
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from creators.models import Creator
from .forms import ConversationFormS, ConversationFormL, MessageForm
from .models import Conversation, Message, GPTModelChoices, MessageRoleChoices
from .gpt_request_parser import generate_message,add_token, generate_stream_message

logger=logging.getLogger()

# Create your views here.

# @login_required
# def one_chat(request):
#     """ render main chat page"""
#     owner_id = Creator.objects.get(user_id=request.user)
#     # get list of conversations
#     return render(request, "conversation.html", {"user":owner_id })

####################################################################
# Cheat sheet for filtering in django model:
# Greater than:
# Person.objects.filter(age__gt=20)
# Greater than or equal to:
# Person.objects.filter(age__gte=20)
# Less than:
# Person.objects.filter(age__lt=20)
# Less than or equal to:
# Person.objects.filter(age__lte=20)
####################################################################

@login_required
@require_GET
def gptutils(request):
    """render main chat page"""
    context=__get_basic_context(request)
    context["is_visual_model"]=True
    return render(request, "conversation.html", context=context)

@login_required
def get_chat(request, conv_pk):
    """ send text request when request is get, return the chat page, when is post, add new message and set completion
    
    Args:
        conv_pk: primary key for Conversation objects

    Returns:
        request.POST:
            streaming: return htmx message pair for streaming (100ms)
            non-streaming: reload page until request to openAI is complete (5s on average)
        request.GET:
            streaming: return infinite scrolling result (default load 10 more messages)
    """
    logger.info(f'request from user {request.user}')
    # processing sending in AJAX (to be implement)
    context = __get_basic_context(request)
    cur_conversation = get_object_or_404(Conversation, id=conv_pk)
    context["cur_conversation"] = cur_conversation
    context["is_visual_model"] = cur_conversation.is_visual_model()
    if cur_conversation.creator_id != context["user"]:
        messages.error(request, f"no permission for edit the conversation")
        return redirect("gptutils:main")
    if request.method == "POST":
        # permission check
        message_form = MessageForm(request.POST, request.FILES)
        if not message_form.is_valid():
            load_form_error_to_messages(request,message_form)
            return render(request, "conversation.html", context=context)
        message_instance = message_form.save(commit=False)
        message_instance.conversation_id = cur_conversation
        response={}

        # processing plain request ajax
        if cur_conversation.model==GPTModelChoices.PLAIN:
            # for plain message, we do nothing but return rendered new message 
            messages_list=Message.objects.filter(conversation_id=conv_pk).order_by("-created")[:1]
            is_last_user=len(messages_list)==0 or messages_list[0].role==MessageRoleChoices.USER
            if is_last_user:
                message_instance.role=MessageRoleChoices.ASSISTANT
            message_instance.save()
            context["messages_list"] = [message_instance]
            # if request is post, then render new pair of message.
            if request.META.get('HTTP_HX_REQUEST'):
                return render(request, "htmx_message_blocks.html", context=context)
        
        # for other AI model, we test for streaming, streaming is an ajax only feature.
        message_instance.save()
        is_streaming=request.POST.get("streaming",False)
        if is_streaming:
            # create dummy message, text cannot be null, so we set it to blank?
            dummy_message=Message.objects.create(conversation_id=cur_conversation,role=MessageRoleChoices.ASSISTANT,text="")
            context["user_msg"]=message_instance
            context["assist_msg"]=dummy_message
            return render(request, "htmx_message_pair_streaming.html", context=context)
        else:
            add_token(message_instance)
            response=generate_message(cur_conversation)
            if "error" in response:
                messages.error(request, f"open-ai error: {response}")
                # if there is error, we cannot do ajax to notify user yet
                # return render(request, "conversation.html", context=context)
                context["messages_list"] = []
                return render(request, "htmx_message_blocks.html", context=context)
            if request.META.get('HTTP_HX_REQUEST'):
                # get most recent message, you can save this query but I don't care.
                context["messages_list"] = Message.objects.filter(conversation_id=conv_pk).order_by("-created")[:2]
                return render(request, "htmx_message_blocks.html", context=context)
        # all post request for this function terminates here.

    # processing get request from htmx (infinite scroll section requests)
    if request.META.get('HTTP_HX_REQUEST'):
        # if request is get, then render new message for infinite scroll
        if request.method=="GET":
            # for the timezone, since our app is running in UTC, remember to change it if you want other timezone.
            after_time=datetime.strptime(request.GET.get("after",""),"%Y-%m-%d %H:%M[:%S[.%f][%Z]").replace(tzinfo=timezone.utc)
            messages_list = Message.objects.filter(conversation_id=conv_pk,created__lt=after_time).order_by("-created")[:10]
            context["messages_list"] = messages_list
            # specify infinite scroll 
            context["infinite_scroll"] = True
            return render(request, "htmx_message_blocks.html", context=context)
    
    # processing response normally, non ajax
    messages_list = Message.objects.filter(conversation_id=conv_pk).order_by("-created")[:10]
    context["messages_list"] = messages_list
    return render(request, "conversation.html", context=context)

@login_required
def get_stream_chat(request, conv_pk):
    """ send text request based on streaming, this function is a bit complex if we add login request
    so we directly allow all the users to make request with strict permission check

    Args:
        conv_pk: primary key for Conversation objects
    """
    # owner_id = get_object_or_None(Creator, user_id=request.user)
    # if owner_id==None:
    #     yield "User not found."
    #     return
    cur_conversation = get_object_or_None(Conversation, id=conv_pk)
    # if cur_conversation==None:
    #     yield "Conversation not found."
    #     return
    logger.info(f'requested streaming chat instance edit form with id {conv_pk}')
    # if cur_conversation.creator_id!=owner_id:
    #     yield "You don't have permission to streaming this conversation."
    #     return
    return StreamingHttpResponse(generate_stream_message(cur_conversation))


@login_required
def create_chat(request):
    """create chat based on conversation form received from user
    
    Args:
        request.POST only.

    Returns:
        redirect to char page if creation is success, else back to gptutils main page.
    """
    # test for user
    owner_id = get_object_or_404(Creator, user_id=request.user)
    if request.method == "POST":
        form_type = request.POST.get("form_type", "invalid")
        if form_type == "invalid":
            messages.error(request, f"form type not found or invalid")
        chat_form = (
            ConversationFormL(request.POST, request.FILES)
            if form_type == "advanced"
            else ConversationFormS(request.POST)
        )
        if chat_form.is_valid():
            chat_instance = chat_form.save(commit=False)
            chat_instance.sharing_id = generate_unique_id(Conversation,"sharing_id")
            chat_instance.creator_id = owner_id
            chat_instance.save()
            return redirect("gptutils:get_chat", conv_pk=chat_instance.id)
        else:
            load_form_error_to_messages(request,chat_form)
    return redirect("gptutils:main")

@login_required
@require_POST
def fast_chat(request):
    """create chat based on conversation form received from user
    I don't want to do any ajax on this section cause it costs a lot of work and don't have much improvement.
    
    Args:
        request.POST only.

    Returns:
        redirect to char page if creation is success, else back to gptutils main page.
    """
    # test for user
    owner_id = get_object_or_404(Creator, user_id=request.user)
    message_form = MessageForm(request.POST, request.FILES)
    if not message_form.is_valid():
        messages.error(request, f"invalid message")
        return redirect("gptutils:main")
    message_instance = message_form.save(commit=False)
    cur_conversation=Conversation.objects.create(creator_id=owner_id,
                                                    sharing_id=generate_unique_id(Conversation,"sharing_id"),
                                                    model=GPTModelChoices.GPT4_V if message_instance.image else GPTModelChoices.GPT4_1106)
    message_instance.conversation_id = cur_conversation
    message_instance.save()
    add_token(message_instance)
    ai_response=generate_message(cur_conversation)
    if not "error" in ai_response:
        return redirect("gptutils:get_chat", conv_pk=cur_conversation.id)
    else:
        messages.warning(request,f"Error when generating response {ai_response['error']}")

notechondria/gptutils/templates/htmx_edit_chat_form.html
<div id="editChatModals">
    <!-- just a place holder for htmx to find -->
    <div class="modal fade" id="deleteChatModal" tabindex="-1" aria-labelledby="deleteChatModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {% if edit_chat_form %}
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteChatModalLabel">Delete chat</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you wish to <strong>DELETE</strong> this chat? All the successive message will be lost!
                    There is currently no way to restore it.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" data-bs-target="#editChatModal" data-bs-toggle="modal"
                        data-bs-dismiss="modal">Back to edit</button>

                    <form action="{% url 'gptutils:delete_chat' edit_chat_form.instance.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger" id="delete-chat-button">Wait 5s</button>
                    </form>
                </div>

                {% else %}
                <div class="alert alert-warning ms-3 me-3 mt-3" role="alert">
                    Edit chat form not received from server
                </div>
                {% endif %}

                {% include "message_display.html"%}
            </div>
        </div>
    </div>

    <div class="modal fade" id="editChatModal" tabindex="-1" aria-labelledby="editChatModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <!-- Use jQuery to hide advanced options -->
                <div class="modal-header">
                    <h5 class="modal-title" id="editChatModalLabel">Edit Chat
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                {% if edit_chat_form %}
                <form action="{% url 'gptutils:edit_chat' edit_chat_form.instance.id %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <!-- Django overkill form -->
                        <!-- Include the hidden fields -->
                        {% for hidden in edit_chat_form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        <!-- Include the visible fields  -->
                        {% for field in edit_chat_form.visible_fields %}
                        <div class="mb-3">
                            {%if field.errors%}
                            <div class="alert alert-danger">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            <label for="{{ field.id_for_label }}" class="form-label">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.help_text %}
                            <div class="form-text">{{ field.help_text|safe }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <div class="row w-100 justify-content-between">
                            <div class="col">
                                <button type="button" class="btn btn-danger" id="deleteChatModalToggle"
                                    data-bs-target="#deleteChatModal" data-bs-toggle="modal"
                                    data-bs-dismiss="modal">Delete
                                    Chat</button>
                            </div>
                            <div class="col-auto">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
                {% else %}
                <div class="modal-body">
                    <div class="alert alert-warning ms-3 me-3 mt-3" role="alert">
                        Edit chat form not received from server
                    </div>
                </div>
                {% endif %}

                {% include "message_display.html"%}
            </div>
        </div>
    </div>
</div>

<!-- load modal on default -->

<script>
    $(document).ready(function () {
        $('#editChatModal').modal('show');
    });

    $("#deleteChatModalToggle").click(function () {
        $('#delete-chat-button').prop('disabled', true);
        setTimeout(function () {
            $("#delete-chat-button").html('Wait 4s');
        }, 1000);
        setTimeout(function () {
            $("#delete-chat-button").html('Wait 3s');
        }, 2000);
        setTimeout(function () {
            $("#delete-chat-button").html('Wait 2s');
        }, 3000);
        setTimeout(function () {
            $("#delete-chat-button").html('Wait 1s');
        }, 4000);
        setTimeout(function () {
            $("#delete-chat-button").prop('disabled', false);
            $("#delete-chat-button").html('Delete');
        }, 5000);

    });
</script>
</div>

notechondria/gptutils/templates/htmx_edit_message_form.html
{% if edit_message_form%}
<!-- Modal -->
<div class="modal fade" id="delete-{{edit_message_form.instance.id}}-Modal" tabindex="-1" aria-labelledby="delete-{{edit_message_form.instance.id}}-ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="delete-{{edit_message_form.instance.id}}-ModalLabel">Delete message</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you wish to <strong>DELETE</strong> the message? All the successive message will be lost! There is currently no way to restore it.
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            
            <form action="{% url 'gptutils:delete_message' edit_message_form.instance.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger" id="delete-{{edit_message_form.instance.id}}-button">Wait 5s</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="msg-edit-form w-100" id="msg-edit-{{edit_message_form.instance.id}}">
    <form class="row justify-content-end mt-2 w-100" id="message-edit-{{edit_message_form.instance.id}}-form"
        action="{% url 'gptutils:edit_message' edit_message_form.instance.id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Django overkill form -->
        <!-- Include the hidden fields -->
        {% for hidden in edit_message_form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        <!-- Include the visible fields  -->
        {% for field in edit_message_form.visible_fields %}
        {% if field.name == "text" %}
        <div class="col-9">
            <label for="{{ field.id_for_label }}" class="visually-hidden">
                {{ field.label }}
            </label>
            {{ field }}
        </div>
        {% elif field.name == "image" and edit_message_form.instance.is_visual_model %}
        <div class="col-3">
            <label for="{{ field.id_for_label }}" class="visually-hidden">
                {{ field.label }}
            </label>
            {{ field }}
        </div>
        {% endif %}
        {% endfor %}
    </form>
    <div class="row g-2">
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mt-2 loading" form="message-edit-{{edit_message_form.instance.id}}-form">Save</button>
        </div>
        <div class="col-auto">
            <button type="button" class="btn btn-danger mt-2" data-bs-toggle="modal" data-bs-target="#delete-{{edit_message_form.instance.id}}-Modal" id="delete-{{edit_message_form.instance.id}}-ModalToggle">
                Delete
              </button>
        </div>
        <div class="col-auto">
            <button class="btn btn-secondary mt-2" id="cancel-edit-{{edit_message_form.instance.id}}">Cancel</button>
        </div>
    </div>
</div>

<!-- turn off msg and open self -->

<script>
    $(document).ready(function () {
        $('#msg-{{edit_message_form.instance.id}}').hide();
        $('#msg-edit-{{edit_message_form.instance.id}}').show();
    });

    $("#cancel-edit-{{edit_message_form.instance.id}}").click(function () {
        $('#msg-{{edit_message_form.instance.id}}').show();
        $('#msg-edit-{{edit_message_form.instance.id}}').hide();
    });

    $("#delete-{{edit_message_form.instance.id}}-ModalToggle").click(function (){
        $('#delete-{{edit_message_form.instance.id}}-button').prop('disabled', true);
        setTimeout(function(){
            $("#delete-{{edit_message_form.instance.id}}-button").html('Wait 4s');
        }, 1000);
        setTimeout(function(){
            $("#delete-{{edit_message_form.instance.id}}-button").html('Wait 3s');
        }, 2000);
        setTimeout(function(){
            $("#delete-{{edit_message_form.instance.id}}-button").html('Wait 2s');
        }, 3000);
        setTimeout(function(){
            $("#delete-{{edit_message_form.instance.id}}-button").html('Wait 1s');
        }, 4000);
        setTimeout(function(){
            $("#delete-{{edit_message_form.instance.id}}-button").prop('disabled', false);
            $("#delete-{{edit_message_form.instance.id}}-button").html('Delete');
        }, 5000);

    });
</script>

{% else %}
<div class="alert alert-warning ms-3 me-3 mt-3" role="alert">
    Edit message form not received from server
</div>
{% endif %}

{% include "message_display.html"%}

notechondria/gptutils/templates/htmx_message_pair_streaming.html
{% load svg_tags %}

<div id="latest-message">
    <!-- place to add new message for ajax post request -->
</div>

<!-- Render latest pair of information -->
<div class="row ps-2 pe-5">
    <div class="col-auto">
        {% if assist_msg %}
        <div class="alert alert-secondary" role="alert">
            <div class="text-muted">{{assist_msg.created_local}}</div>
            <div class="col-auto">
                <div hx-ext="sse" hx-get="{% url 'gptutils:get_stream_chat' assist_msg.conversation_id.id %}" hx-trigger="load" hx-swap="innerHTML">
                    <div class="spinner-grow spinner-grow-sm mt-2" role="status">
                        <span class="visually-hidden">Loading...</span>
                      </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="alert alert-danger" role="alert">
            No assistant message received from server.
        </div>
        {% endif %}
    </div>
</div>

<div class="row d-flex justify-content-end pe-2 ps-5">
    <div class="col-auto">
        {% if user_msg %}
        <div class="alert alert-primary" role="alert">
            <div class="text-muted">{{user_msg.created_local}}</div>
            <div class="msg-edit-form" id="msg-edit-{{user_msg.id}}"></div>
            <div class="user-msg" id="msg-{{user_msg.id}}">
                {{user_msg.body|linebreaksbr}}
                {% if user_msg.extras != None %}
                <div class="collapse" id="collapseMessage-{{user_msg.id}}">{{user_msg.extras|linebreaksbr}}</div>
                <a class="link-dark" data-bs-toggle="collapse" href="#collapseMessage-{{user_msg.id}}" role="button"
                    aria-expanded="false" aria-controls="collapseMessage-{{user_msg.id}}">
                    ...
                </a>
                {% endif %}
                {% if user_msg.image %}
                <img src="{{ user_msg.image.url }}" alt="image send on message {{user_msg.id}}" class="img-fluid"
                    style=" border-radius: 25px;" />
                {% endif %}
                <!-- begin for menu of user input -->
                <div class="edit-icon ">
                    <div class=" row align-items-center">
                        <div class="col-auto">
                            <!-- have a button POST a click via AJAX -->
                            <div id="edit-msg-{{user_msg.id}}"
                                hx-get="{% url 'gptutils:edit_message' user_msg.id %}"
                                hx-target="#msg-edit-{{user_msg.id}}" hx-swap="outerHTML">
                                {% svg_tags 'pen' '' 10 'var(--bs-secondary)' %}
                            </div>
                        </div>
                        <div class="col-auto">
                            <form action="{% url 'gptutils:resend_message' user_msg.id %}" method="post">
                                <!-- csrf_token for request -->
                                {% csrf_token %}
                                <button class="btn btn-link loading" type="submit">
                                {% svg_tags 'arrow-counterclockwise' '' 10 'var(--bs-secondary)' %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- end for menu of user input -->
            </div>
        </div>
        {% else %}
        <div class="alert alert-danger" role="alert">
            No user message received from server.
        </div>
        {% endif %}
    </div>
</div>

{% include "message_display.html"%}