notecondria/creators/urls.py
"""
Mapping the url requrest

This file maps the url requrest from member app and share it with notecondria.url
"""

from django.urls import path
from . import views
urlpatterns = [
    path('', views.creators, name='creators'),
    path('login/',views.login_request,name='login'),
    path('register/',views.register_request,name='register'),
    path('profile/<str:username>',views.get_profile,name='profile'),
    path('profile/<str:username>/edit',views.edit_profile,name='edit_profile'),
    path('logout/',views.logout_request,name="logout")
]

notecondria/gptutils/urls.py
"""
Mapping the url requrest

This file maps the url requrest from member app and share it with notecondria.url
"""

from django.urls import path
from . import views
urlpatterns = [
    path('', views.gptutils, name='main'),
    path('send/<int:pk>',views.send,name='send'),
    path('chat/<int:pk>',views.get_chat,name='get_chat'),
    path('create/',views.create_chat,name='create_chat'),
    path('one/',views.one_chat,name='one')
]

notecondria/notecondria/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path,re_path
from django.views.static import serve
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('notes/', include(('notes.urls','notes'),namespace='notes')),
    path('creators/', include(('creators.urls','creators'),namespace='creators')),
    path('gptutils/', include(('gptutils.urls','recipes'),namespace='gptutils')),
    path('about/',views.about,name="about"),
    path('search/',views.about,name="search"),
    path('admin/', admin.site.urls),
]

# ... the rest of your URLconf goes here ...

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

notecondria/notes/urls.py
"""
Mapping the url requrest

This file maps the url requrest from member app and share it with notecondria.url
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_notes, name='notes'),
    path('snippets/new',views.quick_notes,name='add_snippets'),
    path('notes/new',views.new_notes,name='add_notes'),
    path('notes/',views.get_note,name='add_notes'),
]

notecondria/gptutils/templates/conversation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notecondria About</title>
    <meta charset="UTF-8">
    
    <!-- only load icon when we have to... -->
    {% load bootstrap_icons %}
    
    {% include "resource_header.html" %}
    
</head>

<body>

    {% include "navbar.html" %}

    <div class="modal fade" id="createChatModal" tabindex="-1" aria-labelledby="createChatModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{% url 'gptutils:create_chat' %}" method="post">
                    <!-- Use jQuery to hide advanced options -->
                    <div class="modal-header">
                        <h5 class="modal-title" id="createAdvancedChatModalLabel">Create A New Chat</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        {% if create_form %}
                        {% csrf_token %}
                        <!-- Django overkill form -->
                        <!-- Include the hidden fields -->
                        {% for hidden in create_form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        <!-- Include the visible fields  -->
                        {% for field in create_form.visible_fields %}
                        {% if field.label == 'New image'%}
                        <img src="{{form.instance.image.url }}" class="card-img-top" style="width:100%; height: auto;"
                            alt="profile picture">

                        <div class="mt-3">
                            <!-- render errors -->
                            {%if field.errors%}
                            <div class="alert alert-danger">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            <!-- render label and fields -->
                            <label for="{{ field.id_for_label }}" class="form-label">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            <!-- render help text -->
                            {% if field.help_text %}
                            <div class="form-text">{{ field.help_text|safe }}</div>
                            {% endif %}
                        </div>

                        {% else %}
                        <div class="mt-3">
                            {%if field.errors%}
                            <div class="alert alert-danger">
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            <label for="{{ field.id_for_label }}" class="form-label">
                                {{ field.label }}
                            </label>
                            {{ field }}
                            {% if field.help_text %}
                            <div class="form-text">{{ field.help_text|safe }}</div>
                            {% endif %}
                        </div>

                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Create Chat</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <main class="container-fluid mt-3">
        <div class="row g-2">
            <aside class="col-md-3 blog-sidebar mt-3">
                <div class="card">
                    <div class="card-header d-flex justify-content-end">
                        <a class="link-dark" data-bs-toggle="modal" href="#createChatModal" role="button">
                            {% bs_icon 'plus-circle' size='2em' %}
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="d-flex align-items-stretch">
                            <ul class="list-group list-group-flush" style="height: 100%; overflow-y: scroll;">
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                                <li class="list-group-item">An item</li>
                                <li class="list-group-item">A second item</li>
                                <li class="list-group-item">A third item</li>
                                <li class="list-group-item">A fourth item</li>
                                <li class="list-group-item">And a fifth one</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </aside>
            <div class="col mt-3">
                <div class="h-100 card">
                    <div class="card-body">
                        <!-- Render conversation info -->
                        {%if message_list%}
                        {%else%}
                        <div class="h-100 position-relative">
                            <div class="position-absolute top-50 start-50 translate-middle">
                                <a class="link-dark" data-bs-toggle="modal" href="#createChatModal" role="button">Create
                                    a
                                    chat with advanced configuration</a>
                            </div>
                        </div>
                        {%endif%}
                    </div>
                    <div class="card-footer">

                    </div>
                </div>
                <form>

                </form>
            </div>
        </div>
    </main>
</body>

<!-- TODO: create footer here -->

notecondria/notecondria/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notecondria About</title>
    <meta charset="UTF-8">

    {% include "resource_header.html" %}
</head>

<body>

    {% include "navbar.html" %}

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <section class="bg-light p-5 my-5">
                <h1 id="notecondria" class="display-4 text-center mb-4">Notecondria</h1>
                <p class="lead text-center mb-5">Empower your success with the notes you create.</p>

                <p class="mb-4">Last updated on <time datetime="2023-12-04">December 4, 2023</time>.</p>

                <p class="mb-4">
                    Inspired by the synergy of notes and the energy-producing mitochondria, <strong>Notecondria</strong>
                    is designed to be the catalyst for your personal achievements. Our vision extends beyond mere text
                    or sketches on an iPad or other media. We aim to interconnect all forms of data, weaving them into
                    an easily navigable information tapestry tailored to each user.
                </p>

                <h2 class="h4 mb-3">Key Features:</h2>
                <ul class="mb-4 text-left container">
                    <li>Intelligent note-linking with automated tagging powered by generative AI.</li>
                    <li>Enhanced note interpretation and sharing through generative AI.</li>
                    <li>Effortless synchronization of notes across devices and formats, including images, datasets,
                        LaTeX, Markdown, and more.</li>
                    <li>Dynamic, card-like note truncation and automated daily note generation based on user activity.
                    </li>
                </ul>

                <p class="mb-4">
                    We value your privacy and trust. That's why we guarantee that your data will not be shared or sold
                    to any third parties. As primary users of the app, the developers uphold this commitment.
                </p>

                <p class="mb-0">
                    Your knowledge remains yours alone. Leveraging the OpenAI API, we ensure your original ideas and
                    thoughts are never used for AI training purposes, safeguarding the uniqueness of your intellectual
                    property.
                </p>
            </section>
        </div>
    </section>
</body>

<!-- TODO: create footer here -->

notecondria/notecondria/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Notecondria</title>
    <meta charset="UTF-8">

    {% include "resource_header.html" %}
</head>

<body>

    {% include "navbar.html" %}

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
            </div>
        </div>
    </section>
</body>

<!-- TODO: create footer here -->

notecondria/notecondria/templates/navbar.html
<header class="mb-auto">
    <!-- Nav bar use some code from: https://getbootstrap.com/docs/5.3/components/navbar/#scrolling -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <!-- Title -->
            <a class="navbar-brand ml-3" href="#">Notecondria</a>
            <!-- Toggle for navigation bar if there is no enough space -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Toggle content (navigation bar) -->
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <!-- Homepage -->
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <!-- Extra link -->
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'about'%}">About</a>
                    </li>

                    {% if user.is_authenticated %}
                    <!-- Extra dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Notes
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{%url 'notes:add_snippets' %}">Add snippets</a></li>
                            <li><a class="dropdown-item" href="{%url 'notes:add_notes' %}">Create notes</a></li>
                        </ul>
                    </li>
                    <!-- Extra dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Utilities
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{%url 'gptutils:main' %}">Start conversation</a></li>
                            <li><a class="dropdown-item" href="{%url 'gptutils:one' %}">One-time request</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>

                <!-- Search bar -->
                <form class="d-flex ms-auto me-auto" action="{% url 'search' %}" role="search" method="post">
                    {% csrf_token %}
                    <input class="form-control me-2" type="text" name="query" placeholder="{% if query%}{{query}}{% else %}Enter to start serach{%endif%}">
                    <button class="btn btn btn-outline-success" type="submit">Search</button>
                </form>

                <!-- User info -->
                {% if user.is_authenticated %}
                <a class="btn btn-primary ms-3" href="{% url 'creators:profile' user.username %}">Setting</a>
                <a class="btn btn-primary ms-3" href="{% url 'creators:logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-primary ms-3" href="{% url 'creators:login' %}">Login</a>
                <!-- TODO: Make this function -->
                <a class="btn btn-primary ms-3" href="{% url 'creators:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="{% if message.tags %}{% if message.tags == 'debug' %}alert alert-light{% elif message.tags == 'error'%}alert alert-danger{% else %}alert alert-{{message.tags}}{% endif %}{% endif %} mb-3">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
</header>